language: ruby
rvm:
  - 2.1
env:
  - DB=postgres
script:
  - gem install tilt -v '1.4.1'
  - gem install byebug -v '3.5.1'
  - cp config/secrets.yml.sample config/secrets.yml
  - RAILS_ENV=test bundle exec rake db:create db:migrate test
services:
  - redis-server
