default: &default
  username: postgres
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ul_lider_development

test:
  <<: *default
  database: ul_lider_test

staging:
  <<: *default
  username: lider
  database: ul_lider_staging

production:
  <<: *default
  username: lider
  database: ul_lider_production
