Page.find_or_create_by slug: 'definition'
Page.find_or_create_by slug: 'stage_1'
Page.find_or_create_by slug: 'stage_2'
Page.find_or_create_by slug: 'stage_3'
Page.find_or_create_by slug: 'privacy'
Page.find_or_create_by slug: 'the_competition'
